language: cpp
compiler: gcc
script:
  - sh tools/get_pthsem
  - sh -x bootstrap.sh
  - env CFLAGS="-Wall -Wextra" CPPFLAGS="-Wall -Wextra" ./configure --with-pth=$HOME/pthsem --without-pth-test --disable-systemd
  - make
  - env LD_LIBRARY_PATH=$HOME/pthsem/lib sh tools/test.sh
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
    - $HOME/pthsem
sudo: false
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
